#/system/bin/sh
# Copyright (c) 2025, Noah Y. & Xaiphon

CON_PATH="/sdcard/Android/SpeedSaver"

# Wait until boot completed
    until [ $(resetprop sys.boot_completed) -eq 1 ] &&
        [ -d /sdcard ]; do
        sleep 10
    done

# Check if the directory exists
if [ -d "$CON_PATH" ]; then
    # Delete the directory and all its contents
    rm -rf "$CON_PATH"
fi

# Renove global table modifications
settings delete global cached_apps_freezer
#settings delete global enable_screen_on_proximity_sensor
settings delete global fstrim_mandatory_interval

# Reverse deactivation of Android Rescue Party
setprop persist.sys.disable_rescue false
resetprop -p persist.sys.disable_rescue false

# Enable GMS services
pm enable com.google.android.gms/.ads.settings.AdsSettingsActivity
pm enable com.google.android.gms/com.google.android.location.places.ui.aliaseditor.AliasEditorActivity
pm enable com.google.android.gms/com.google.android.location.places.ui.aliaseditor.AliasEditorMapActivity
pm enable com.google.android.gms/com.google.android.location.settings.ActivityRecognitionPermissionActivity
pm enable com.google.android.gms/com.google.android.location.settings.GoogleLocationSettingsActivity
pm enable com.google.android.gms/com.google.android.location.settings.LocationHistorySettingsActivity
pm enable com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity
pm enable com.google.android.gms/.usagereporting.settings.UsageReportingActivity
pm enable com.google.android.gms/.googlehelp.helpactivities.SystemAppTrampolineActivity
pm enable com.google.android.gms/.feedback.AnnotateScreenshotActivity
pm enable com.google.android.gms/.ads.adinfo.AdvertisingInfoContentProvider
pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingContentProvider
pm enable com.google.android.gms/com.google.android.location.internal.LocationContentProvider
pm enable com.google.android.gms/.common.stats.net.contentprovider.NetworkUsageContentProvider
pm enable com.google.android.gms/.ads.config.GServicesChangedReceiver
pm enable com.google.android.gms/com.google.android.contextmanager.systemstate.SystemStateReceiver
pm enable com.google.android.gms/.ads.jams.SystemEventReceiver
pm enable com.google.android.gms/.ads.config.FlagsReceiver
pm enable com.google.android.gms/.ads.social.DoritosReceiver
pm enable com.google.android.gms/.analytics.AnalyticsReceiver
pm enable com.google.android.gms/.analytics.internal.GServicesChangedReceiver
pm enable com.google.android.gms/.common.analytics.CoreAnalyticsReceiver
pm enable com.google.android.gms/.common.stats.GmsCoreStatsServiceLauncher
pm enable com.google.android.gms/com.google.android.location.internal.AnalyticsSamplerReceiver
pm enable com.google.android.gms/.checkin.CheckinService$ActiveReceiver
pm enable com.google.android.gms/.checkin.CheckinService$ClockworkFallbackReceiver
pm enable com.google.android.gms/.checkin.CheckinService$ImposeReceiver
pm enable com.google.android.gms/.checkin.CheckinService$SecretCodeReceiver
pm enable com.google.android.gms/.checkin.CheckinService$TriggerReceiver
pm enable com.google.android.gms/.checkin.EventLogService$Receiver
pm enable com.google.android.gms/com.google.android.location.reporting.service.ExternalChangeReceiver
pm enable com.google.android.gms/com.google.android.location.reporting.service.GcmRegistrationReceiver
pm enable com.google.android.gms/com.google.android.location.copresence.GcmRegistrationReceiver
pm enable com.google.android.gms/com.google.android.location.copresence.GservicesBroadcastReceiver
pm enable com.google.android.gms/com.google.android.location.internal.LocationProviderEnabler
pm enable com.google.android.gms/com.google.android.location.internal.NlpNetworkProviderSettingsUpdateReceiver
pm enable com.google.android.gms/com.google.android.location.network.ConfirmAlertActivity$LocationModeChangingReceiver
pm enable com.google.android.gms/com.google.android.location.places.ImplicitSignalsReceiver
pm enable com.google.android.gms/com.google.android.libraries.social.mediamonitor.MediaMonitor
pm enable com.google.android.gms/.location.copresence.GcmBroadcastReceiver
pm enable com.google.android.gms/.location.reporting.service.GcmBroadcastReceiver
pm enable com.google.android.gms/.social.location.GservicesBroadcastReceiver
pm enable com.google.android.gms/.update.SystemUpdateService$Receiver
pm enable com.google.android.gms/.update.SystemUpdateService$OtaPolicyReceiver
pm enable com.google.android.gms/.update.SystemUpdateService$SecretCodeReceiver
pm enable com.google.android.gms/.update.SystemUpdateService$ActiveReceiver
pm enable com.google.android.gms/com.google.android.contextmanager.service.ContextManagerService
pm enable com.google.android.gms/.ads.AdRequestBrokerService
pm enable com.google.android.gms/.ads.GservicesValueBrokerService
pm enable com.google.android.gms/.ads.identifier.service.AdvertisingIdNotificationService
pm enable com.google.android.gms/.ads.identifier.service.AdvertisingIdService
pm enable com.google.android.gms/.ads.jams.NegotiationService
pm enable com.google.android.gms/.ads.pan.PanService
pm enable com.google.android.gms/.ads.social.GcmSchedulerWakeupService
pm enable com.google.android.gms/.analytics.AnalyticsService
pm enable com.google.android.gms/.analytics.internal.PlayLogReportingService
pm enable com.google.android.gms/.analytics.service.AnalyticsService
pm enable com.google.android.gms/.analytics.service.PlayLogMonitorIntervalService
pm enable com.google.android.gms/.analytics.service.RefreshEnabledStateService
pm enable com.google.android.gms/.auth.be.proximity.authorization.userpresence.UserPresenceService
pm enable com.google.android.gms/.common.analytics.CoreAnalyticsIntentService
pm enable com.google.android.gms/.common.stats.GmsCoreStatsService
pm enable com.google.android.gms/.backup.BackupStatsService
pm enable com.google.android.gms/.deviceconnection.service.DeviceConnectionAsyncService
pm enable com.google.android.gms/.deviceconnection.service.DeviceConnectionServiceBroker
pm enable com.google.android.gms/.wallet.service.analytics.AnalyticsIntentService
pm enable com.google.android.gms/.checkin.CheckinService
pm enable com.google.android.gms/.checkin.EventLogService
pm enable com.google.android.gms/com.google.android.location.internal.AnalyticsUploadIntentService
pm enable com.google.android.gms/com.google.android.location.reporting.service.DeleteHistoryService
pm enable com.google.android.gms/com.google.android.location.reporting.service.DispatchingService
pm enable com.google.android.gms/com.google.android.location.reporting.service.InternalPreferenceServiceDoNotUse
pm enable com.google.android.gms/com.google.android.location.reporting.service.LocationHistoryInjectorService
pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingAndroidService
pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingSyncService
pm enable com.google.android.gms/com.google.android.location.activity.HardwareArProviderService
pm enable com.google.android.gms/com.google.android.location.fused.FusedLocationService
pm enable com.google.android.gms/com.google.android.location.fused.service.FusedProviderService
pm enable com.google.android.gms/com.google.android.location.geocode.GeocodeService
pm enable com.google.android.gms/com.google.android.location.geofencer.service.GeofenceProviderService
pm enable com.google.android.gms/com.google.android.location.internal.GoogleLocationManagerService
pm enable com.google.android.gms/com.google.android.location.places.PlaylogService
pm enable com.google.android.gms/com.google.android.location.places.service.GeoDataService
pm enable com.google.android.gms/com.google.android.location.places.service.PlaceDetectionService
pm enable com.google.android.gms/com.google.android.libraries.social.mediamonitor.MediaMonitorIntentService
pm enable com.google.android.gms/.config.ConfigService
pm enable com.google.android.gms/.stats.PlatformStatsCollectorService
pm enable com.google.android.gms/.usagereporting.service.UsageReportingService
pm enable com.google.android.gms/.update.SystemUpdateService
pm enable com.google.android.gms/com.google.android.location.network.ConfirmAlertActivity
pm enable com.google.android.gms/com.google.android.location.network.LocationProviderChangeReceiver
pm enable com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService
pm enable com.google.android.gms/com.google.android.location.internal.PendingIntentCallbackService
pm enable com.google.android.gms/com.google.android.location.network.NetworkLocationService
pm enable com.google.android.gms/com.google.android.location.util.PreferenceService
pm enable com.google.android.gms/.fitness.settings.FitnessSettingsActivity
pm enable com.google.android.gms/.fitness.sync.FitnessContentProvider
pm enable com.google.android.gms/.fitness.disconnect.FitDisconnectReceiver
pm enable com.google.android.gms/.fitness.sensors.sample.CollectSensorReceiver
pm enable com.google.android.gms/.fitness.service.FitnessInitReceiver
pm enable com.google.android.gms/.fitness.wearables.WearableSyncServiceReceiver
pm enable com.google.android.gms/.fitness.disconnect.FitCleanupService
pm enable com.google.android.gms/.fitness.sensors.activity.ActivityRecognitionService
pm enable com.google.android.gms/.fitness.sensors.floorchange.FloorChangeRecognitionService
pm enable com.google.android.gms/.fitness.sensors.sample.CollectSensorService
pm enable com.google.android.gms/.fitness.service.DebugIntentService
pm enable com.google.android.gms/.fitness.service.ble.FitBleBroker
pm enable com.google.android.gms/.fitness.service.config.FitConfigBroker
pm enable com.google.android.gms/.fitness.service.history.FitHistoryBroker
pm enable com.google.android.gms/.fitness.service.internal.FitInternalBroker
pm enable com.google.android.gms/.fitness.service.proxy.FitProxyBroker
pm enable com.google.android.gms/.fitness.service.recording.FitRecordingBroker
pm enable com.google.android.gms/.fitness.service.sensors.FitSensorsBroker
pm enable com.google.android.gms/.fitness.service.sessions.FitSessionsBroker
pm enable com.google.android.gms/.fitness.store.maintenance.StoreMaintenanceService
pm enable com.google.android.gms/.fitness.sync.FitnessSyncAdapterService
pm enable com.google.android.gms/.fitness.wearables.WearableSyncService
pm enable com.google.android.gms/.car.BroadcastRedirectActivity
pm enable com.google.android.gms/.car.CarErrorDisplayActivity
pm enable com.google.android.gms/.car.CarHomeActivity
pm enable com.google.android.gms/.car.CarHomeActivity1
pm enable com.google.android.gms/.car.CarHomeActivity2
pm enable com.google.android.gms/.car.CarServiceSettingsActivity
pm enable com.google.android.gms/.car.FirstActivity
pm enable com.google.android.gms/.car.SetupActivity
pm enable com.google.android.gms/.car.CarIntentService
pm enable com.google.android.gms/.car.CarService
pm enable com.google.android.gms/.car.InCallServiceImpl
pm enable com.google.android.gms/.car.VoiceActionService
pm enable com.google.android.gms/.car.diagnostics.CrashReporterService
pm enable com.google.android.gms/.feedback.FeedbackActivity
pm enable com.google.android.gms/.feedback.IntentListenerFeedbackActivity
pm enable com.google.android.gms/.feedback.PreviewActivity
pm enable com.google.android.gms/.feedback.PreviewScreenshotActivity
pm enable com.google.android.gms/.feedback.ShowTextActivity
pm enable com.google.android.gms/.feedback.SuggestionsActivity
pm enable com.google.android.gms/.feedback.FeedbackConnectivityReceiver
pm enable com.google.android.gms/.feedback.FeedbackAsyncService
pm enable com.google.android.gms/.feedback.FeedbackService
pm enable com.google.android.gms/.feedback.LegacyBugReportService
pm enable com.google.android.gms/.feedback.SendService
pm enable com.google.android.gms/.googlehelp.helpactivities.ClickToCallActivity
pm enable com.google.android.gms/.googlehelp.helpactivities.EmailActivity
pm enable com.google.android.gms/.googlehelp.helpactivities.HelpActivity
pm enable com.google.android.gms/.googlehelp.helpactivities.OpenHangoutActivity
pm enable com.google.android.gms/.googlehelp.helpactivities.OpenHelpActivity
pm enable com.google.android.gms/.googlehelp.helpactivities.RealtimeSupportClassifierActivity
pm enable com.google.android.gms/.googlehelp.webview.GoogleHelpWebViewActivity
pm enable com.google.android.gms/.googlehelp.GcmBroadcastReceiver
pm enable com.google.android.gms/.googlehelp.metrics.ConnectivityBroadcastReceiver
pm enable com.google.android.gms/.googlehelp.metrics.MetricsReportService
pm enable com.google.android.gms/.googlehelp.metrics.ReportBatchedMetricsService
pm enable com.google.android.gms/.googlehelp.service.ChatStatusUpdateService
pm enable com.google.android.gms/.googlehelp.service.ClearHelpHistoryIntentService
pm enable com.google.android.gms/.googlehelp.service.GoogleHelpService
pm enable com.google.android.gms/.googlehelp.service.VideoCallStatusUpdateService
pm enable com.google.android.gms/.kids.account.AccountRemovalConfirmActivity
pm enable com.google.android.gms/.kids.account.AccountSetupActivity
pm enable com.google.android.gms/.kids.account.ShowAppsActivity
pm enable com.google.android.gms/.kids.account.activities.RegisterProfileOwnerActivity
pm enable com.google.android.gms/.kids.creation.activities.FamilyCreationActivity
pm enable com.google.android.gms/.kids.chimera.KidsDataProviderProxy
pm enable com.google.android.gms/.kids.account.receiver.ProfileOwnerReceiver
pm enable com.google.android.gms/.kids.chimera.AccountChangeReceiverProxy
pm enable com.google.android.gms/.kids.chimera.AccountSetupCompletedReceiverProxy
pm enable com.google.android.gms/.kids.chimera.DeviceTimeAndDateChangeReceiverProxy
pm enable com.google.android.gms/.kids.chimera.InternalEventReceiverLmpProxy
pm enable com.google.android.gms/.kids.chimera.InternalEventReceiverProxy
pm enable com.google.android.gms/.kids.chimera.LocationModeChangedReceiverProxy
pm enable com.google.android.gms/.kids.chimera.PackageChangedReceiverProxy
pm enable com.google.android.gms/.kids.chimera.SystemEventReceiverProxy
pm enable com.google.android.gms/.kids.chimera.LongRunningServiceProxy
pm enable com.google.android.gms/.kids.common.sync.ManualSyncReceiver
pm enable com.google.android.gms/.kids.GcmReceiverService
pm enable com.google.android.gms/.kids.chimera.AccountSetupServiceProxy
pm enable com.google.android.gms/.kids.chimera.KidsApiServiceProxy
pm enable com.google.android.gms/.kids.chimera.KidsDataSyncServiceProxy
pm enable com.google.android.gms/.kids.chimera.KidsServiceProxy
pm enable com.google.android.gms/.kids.chimera.SlowOperationServiceProxy
pm enable com.google.android.gms/.kids.chimera.TimeoutsSystemAlertServiceProxy
pm enable com.google.android.gms/.kids.device.RingService
pm enable com.google.android.gms/.nearby.messages.settings.NearbyMessagesAppOptInActivity
pm enable com.google.android.gms/.nearby.settings.NearbyAccessActivity
pm enable com.google.android.gms/.nearby.settings.NearbySettingsActivity
pm enable com.google.android.gms/.nearby.messages.NearbyMessagesBroadcastReceiver
pm enable com.google.android.gms/.nearby.settings.NearbyAppUninstallReceiver
pm enable com.google.android.gms/.nearby.bootstrap.service.NearbyBootstrapService
pm enable com.google.android.gms/.nearby.connection.service.NearbyConnectionsAndroidService
pm enable com.google.android.gms/.nearby.connection.service.NearbyConnectionsAsyncService
pm enable com.google.android.gms/.nearby.messages.service.NearbyMessagesService
pm enable com.google.android.gms/.nearby.sharing.service.NearbySharingService
pm enable com.google.android.gms/.phenotype.receiver.PhenotypeBroadcastReceiver
pm enable com.google.android.gms/.phenotype.service.PhenotypeCommitService
pm enable com.google.android.gms/.phenotype.service.PhenotypeIntentService
pm enable com.google.android.gms/.phenotype.service.PhenotypeService
pm enable com.google.android.gms/.phenotype.service.sync.PhenotypeConfigurator
pm enable com.google.android.gms/.phenotype.service.util.PhenotypeDebugService
pm enable com.google.android.gms/.pseudonymous.service.PseudonymousIdIntentService
pm enable com.google.android.gms/.pseudonymous.service.PseudonymousIdService
pm enable com.google.android.gms/.photos.autobackup.ui.AutoBackupSettingsActivity
pm enable com.google.android.gms/.photos.autobackup.ui.AutoBackupSettingsRedirectActivity
pm enable com.google.android.gms/.photos.autobackup.ui.LocalFoldersBackupSettings
pm enable com.google.android.gms/.photos.autobackup.ui.promo.AutoBackupPromoActivity
pm enable com.google.android.gms/.photos.InitializePhotosIntentReceiver
pm enable com.google.android.gms/.photos.autobackup.AutoBackupWorkService
pm enable com.google.android.gms/.photos.autobackup.service.AutoBackupService
pm enable com.google.android.gms/.playlog.service.MonitorAlarmReceiver
pm enable com.google.android.gms/.playlog.service.WallClockChangedReceiver
pm enable com.google.android.gms/.playlog.service.MonitorService
pm enable com.google.android.gms/.playlog.service.PlayLogBrokerService
pm enable com.google.android.gms/.playlog.service.PlayLogIntentService
pm enable com.google.android.gms/.playlog.uploader.RequestUploadService
pm enable com.google.android.gms/.playlog.uploader.UploaderService
pm enable com.google.android.gms/.plus.activity.AccountSignUpActivity
pm enable com.google.android.gms/.plus.apps.ListAppsActivity
pm enable com.google.android.gms/.plus.apps.ManageAppActivity
pm enable com.google.android.gms/.plus.apps.ManageDeviceActivity
pm enable com.google.android.gms/.plus.apps.ManageMomentActivity
pm enable com.google.android.gms/.plus.audience.AclSelectionActivity
pm enable com.google.android.gms/.plus.audience.AudienceSearchActivity
pm enable com.google.android.gms/.plus.audience.CircleCreationActivity
pm enable com.google.android.gms/.plus.audience.CircleSelectionActivity
pm enable com.google.android.gms/.plus.audience.FaclSelectionActivity
pm enable com.google.android.gms/.plus.audience.UpdateActionOnlyActivity
pm enable com.google.android.gms/.plus.audience.UpdateCirclesActivity
pm enable com.google.android.gms/.plus.circles.AddToCircleConsentActivity
pm enable com.google.android.gms/.plus.oob.PlusActivity
pm enable com.google.android.gms/.plus.oob.UpgradeAccountActivity
pm enable com.google.android.gms/.plus.oob.UpgradeAccountInfoActivity
pm enable com.google.android.gms/.plus.plusone.PlusOneActivity
pm enable com.google.android.gms/.plus.sharebox.AddToCircleActivity
pm enable com.google.android.gms/.plus.sharebox.ReplyBoxActivity
pm enable com.google.android.gms/.plus.sharebox.ShareBoxActivity
pm enable com.google.android.gms/.plus.provider.PlusProvider
pm enable com.google.android.gms/.plus.service.DefaultIntentService
pm enable com.google.android.gms/.plus.service.ImageIntentService
pm enable com.google.android.gms/.plus.service.OfflineActionSyncAdapterService
pm enable com.google.android.gms/.plus.service.PlusService
pm enable com.google.android.gms/.wifi.gatherer2.receiver.WifiStateChangeReceiver
pm enable com.google.android.gms/.wifi.gatherer2.receiver.GoogleAccountChangeReceiver
pm enable com.google.android.gms/.wifi.gatherer2.service.GcmReceiverService
pm enable com.google.android.gms/.wifi.gatherer2.service.WifiUpdateRetryTaskService
pm enable com.google.android.gms/.wifi.gatherer2.service.KeyManagerServce
pm enable com.google.android.gms/.ads.measurement.GmpConversionTrackingBrokerService
pm enable com.google.android.gms/.measurement.service.MeasurementBrokerService
pm enable com.google.android.gms/.perfprofile.uploader.PerfProfileCollectorService
pm enable com.google.android.gms/.perfprofile.uploader.RequestPerfProfileCollectionService
pm enable com.google.android.gsf/.update.SystemUpdateActivity
pm enable com.google.android.gsf/.update.SystemUpdatePanoActivity
pm enable com.google.android.gsf/com.google.android.gsf.checkin.CheckinService\$Receiver
pm enable com.google.android.gsf/com.google.android.gsf.checkin.CheckinService\$SecretCodeReceiver
pm enable com.google.android.gsf/com.google.android.gsf.checkin.CheckinService\$TriggerReceiver
pm enable com.google.android.gsf/.checkin.EventLogService$Receiver
pm enable com.google.android.gsf/.update.SystemUpdateService$Receiver
pm enable com.google.android.gsf/.update.SystemUpdateService$SecretCodeReceiver
pm enable com.google.android.gsf/.checkin.CheckinService
pm enable com.google.android.gsf/.checkin.EventLogService
pm enable com.google.android.gsf/.update.SystemUpdateService
pm enable com.google.android.gms/com.google.android.gms.ads.identifier.service.AdvertisingIdNotificationService
pm enable com.google.android.gms/com.google.android.gms.ads.identifier.service.AdvertisingIdService
pm enable com.google.android.gms/com.google.android.gms.nearby.mediums.nearfieldcommunication.NfcAdvertisingService
pm enable com.google.android.gms/com.google.android.gms.analytics.AnalyticsService
pm enable com.google.android.gms/com.google.android.gms.analytics.AnalyticsTaskService
pm enable com.google.android.gms/com.google.android.gms.analytics.internal.PlayLogReportingService
pm enable com.google.android.gms/com.google.android.gms.stats.eastworld.EastworldService
pm enable com.google.android.gms/com.google.android.gms.stats.service.DropBoxEntryAddedService
pm enable com.google.android.gms/com.google.android.gms.stats.PlatformStatsCollectorService
pm enable com.google.android.gms/com.google.android.gms.common.stats.GmsCoreStatsService
pm enable com.google.android.gms/com.google.android.gms.common.stats.StatsUploadService
pm enable com.google.android.gms/com.google.android.gms.backup.stats.BackupStatsService
pm enable com.google.android.gms/com.google.android.gms.checkin.CheckinApiService
pm enable com.google.android.gms/com.google.android.gms.checkin.CheckinService
pm enable com.google.android.gms/com.google.android.gms.tron.CollectionService
pm enable com.google.android.gms/com.google.android.gms.common.config.PhenotypeCheckinService
pm enable com.google.android.gms/com.google.android.location.internal.server.HardwareArProviderService
pm enable com.google.android.gms/com.google.android.gms.feedback.FeedbackAsyncService
pm enable com.google.android.gms/com.google.android.gms.feedback.LegacyBugReportService
pm enable com.google.android.gms/com.google.android.gms.feedback.OfflineReportSendTaskService
pm enable com.google.android.gms/com.google.android.gms.googlehelp.metrics.ReportBatchedMetricsGcmTaskService
pm enable com.google.android.gms/com.google.android.gms.analytics.internal.PlayLogReportingService
pm enable com.google.android.gms/com.google.android.gms.locationsharingreporter.service.reporting.periodic.PeriodicReporterMonitoringService
pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingAndroidService
pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingSyncService
pm enable com.google.android.gms/com.google.android.gms.common.stats.net.NetworkReportService
pm enable com.google.android.gms/com.google.android.gms.presencemanager.service.PresenceManagerPresenceReportService
pm enable com.google.android.gms/com.google.android.gms.usagereporting.service.UsageReportingIntentService
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRoute2ProviderService
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRoute2ProviderService_Isolated
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRoute2ProviderService_Persistent
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRouteProviderService
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRouteProviderService_Isolated
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRouteProviderService_Persistent
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastRemoteDisplayProviderService
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastRemoteDisplayProviderService_Isolated
pm enable com.google.android.gms/com.google.android.gms.cast.media.CastRemoteDisplayProviderService_Persistent
pm enable com.google.android.gms/com.google.android.gms.cast.service.CastPersistentService_Persistent
pm enable com.google.android.gms/com.google.android.gms.cast.service.CastSocketMultiplexerLifeCycleService
pm enable com.google.android.gms/com.google.android.gms.cast.service.CastSocketMultiplexerLifeCycleService_Isolated
pm enable com.google.android.gms/com.google.android.gms.cast.service.CastSocketMultiplexerLifeCycleService_Persistent
pm enable com.google.android.gms/com.google.android.gms.chimera.CastPersistentBoundBrokerService
pm enable com.google.android.gms/com.google.android.gms.nearby.messages.debug.DebugPokeService
pm enable com.google.android.gms/com.google.android.gms.clearcut.debug.ClearcutDebugDumpService
pm enable com.google.firebase.components.ComponentDiscoveryService
pm enable com.google.android.gms/com.google.android.gms.nearby.discovery.service.DiscoveryService
pm enable com.google.android.gms/com.google.mlkit.common.internal.MlKitComponentDiscoveryService
pm enable com.google.android.gms/com.google.android.gms.geotimezone.GeoTimeZoneService
pm enable com.google.android.gms/com.google.android.gms.location.geocode.GeocodeService
pm enable com.google.android.gms/com.google.android.gms.chimera.GmsIntentOperationService_AuthAccountIsolated com.google.android.gms/com.google.android.gms.chimera.GmsIntentOperationService_AuthAccountIsolate
pm enable com.google.android.gms/com.google.android.gms.chimera.PersistentApiService_AuthAccountIsolated
pm enable com.google.android.gms/com.google.android.gms.chimera.PersistentIntentOperationService_AuthAccountIsolated
pm enable com.google.android.gms/com.google.android.gms.auth.folsom.service.FolsomPublicKeyUpdateService
pm enable com.google.android.gms/com.google.android.gms.fonts.update.UpdateSchedulerService
pm enable com.google.android.gms/com.google.android.gms.icing.proxy.IcingInternalCorporaUpdateService
pm enable com.google.android.gms/com.google.android.gms.instantapps.routing.DomainFilterUpdateService
pm enable com.google.android.gms/com.google.android.gms.mobiledataplan.service.PeriodicUpdaterService
pm enable com.google.android.gms/com.google.android.gms.phenotype.service.sync.PackageUpdateTaskService
pm enable com.google.android.gms/com.google.android.gms.update.SystemUpdateGcmTaskService
pm enable com.google.android.gms/com.google.android.gms.update.SystemUpdateService
pm enable com.google.android.gms/com.google.android.gms.update.UpdateFromSdCardService
pm enable com.google.android.gms/com.google.android.gms.backup.wear.BackupSettingsListenerService
pm enable com.google.android.gms/com.google.android.gms.dck.service.DckWearableListenerService
pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncAccountService
pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncConfigService
pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncConnectionService
pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncMessageService
pm enable com.google.android.gms/com.google.android.gms.fitness.wearables.WearableSyncService
pm enable com.google.android.gms/com.google.android.gms.wearable.service.WearableControlService
pm enable com.google.android.gms/com.google.android.gms.wearable.service.WearableService
#pm enable com.google.android.gms/com.google.android.gms.nearby.fastpair.service.WearableDataListenerService
pm enable com.google.android.gms/com.google.android.location.wearable.WearableLocationService
pm enable com.google.android.gms/com.google.android.location.fused.wearable.GmsWearableListenerService
pm enable com.google.android.gms/com.google.android.gms.mdm.services.MdmPhoneWearableListenerService
pm enable com.google.android.gms/com.google.android.gms.tapandpay.wear.WearProxyService
pm enable com.google.android.gms/com.google.android.gms.auth.trustagent.GoogleTrustAgent
pm enable com.google.android.gms/com.google.android.gms.trustagent.api.bridge.TrustAgentBridgeService
pm enable com.google.android.gms/com.google.android.gms.trustagent.api.state.TrustAgentState
pm enable com.google.android.gms/com.google.android.gms.enpromo.PromoInternalPersistentService
pm enable com.google.android.gms/com.google.android.gms.enpromo.PromoInternalService
pm enable com.google.android.gms/com.google.android.gms.thunderbird.EmergencyLocationService 
pm enable com.google.android.gms/com.google.android.gms.thunderbird.EmergencyPersistentService
pm enable com.google.android.gms/com.google.android.gms.kids.chimera.KidsServiceProxy
pm enable com.google.android.gms/com.google.android.gms.personalsafety.service.PersonalSafetyService
pm enable com.google.android.gms/com.google.android.gms.fitness.cache.DataUpdateListenerCacheService
pm enable com.google.android.gms/com.google.android.gms.fitness.service.ble.FitBleBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.config.FitConfigBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.goals.FitGoalsBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.history.FitHistoryBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.internal.FitInternalBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.proxy.FitProxyBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.recording.FitRecordingBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.sensors.FitSensorsBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.service.sessions.FitSessionsBroker
pm enable com.google.android.gms/com.google.android.gms.fitness.sensors.sample.CollectSensorService
pm enable com.google.android.gms/com.google.android.gms.fitness.sync.FitnessSyncAdapterService 
pm enable com.google.android.gms/com.google.android.gms.fitness.sync.SyncGcmTaskService
pm enable com.google.android.gms/com.google.android.gms.nearby.bootstrap.service.NearbyBootstrapService
pm enable com.google.android.gms/com.google.android.gms.nearby.connection.service.NearbyConnectionsAndroidService
pm enable com.google.android.gms/com.google.location.nearby.direct.service.NearbyDirectService
pm enable com.google.android.gms/com.google.android.gms.nearby.messages.service.NearbyMessagesService
pm enable com.google.android.gms/com.google.android.gms.analytics.internal.PlayLogReportingService
pm enable com.google.android.gms/com.google.android.gms.romanesco.ContactsLoggerUploadService
pm enable com.google.android.gms/com.google.android.gms.magictether.logging.DailyMetricsLoggerService
pm enable com.google.android.gms/com.google.android.gms.checkin.EventLogService
pm enable com.google.android.gms/com.google.android.gms.backup.component.FullBackupJobLoggerService
pm enable com.google.android.gms/com.google.android.gms.security.safebrowsing.SafeBrowsingUpdateTaskService
pm enable com.google.android.gms/com.google.android.gms.security.verifier.ApkUploadService
pm enable com.google.android.gms/com.google.android.gms.security.verifier.InternalApkUploadService
pm enable com.google.android.gms/com.google.android.gms.security.snet.SnetIdleTaskService
pm enable com.google.android.gms/com.google.android.gms.security.snet.SnetNormalTaskService
pm enable com.google.android.gms/com.google.android.gms.security.snet.SnetService
pm enable com.google.android.gms/com.google.android.gms.tapandpay.security.StorageKeyCacheService
pm enable com.google.android.gms/com.google.android.gms.droidguard.DroidGuardGcmTaskService
pm enable com.google.android.gms/com.google.android.gms.pay.security.storagekey.service.StorageKeyCacheService
pm enable com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService
pm enable com.google.android.gms/com.google.android.gms.tapandpay.globalactions.QuickAccessWalletService
pm enable com.google.android.gms/com.google.android.gms.tapandpay.globalactions.WalletQuickAccessWalletService
pm enable com.google.android.gms/com.google.android.gms.pay.gcmtask.PayGcmTaskService
pm enable com.google.android.gms/com.google.android.gms.pay.hce.service.PayHceService
pm enable com.google.android.gms/com.google.android.gms.pay.notifications.PayNotificationService
pm enable com.google.android.gms/com.google.android.gms.wallet.service.PaymentService
pm enable com.google.android.gms/com.google.android.gms.wallet.service.WalletGcmTaskService
pm enable com.google.android.gms/com.google.android.gms.fitness.cache.DataUpdateListenerCacheService
pm enable com.google.android.gms/com.google.android.gms.fitness.sensors.sample.CollectSensorService
pm enable com.google.android.gms/com.google.android.gms.fitness.sync.SyncGcmTaskService
pm enable com.google.android.gms/com.google.android.location.fused.FusedLocationService
pm enable com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService
pm enable com.google.android.gms/com.google.android.location.network.NetworkLocationService
pm enable com.google.android.gms/com.google.android.location.persistent.LocationPersistentService
pm enable com.google.android.gms/com.google.android.location.reporting.service.LocationHistoryInjectorService
pm enable com.google.android.gms/com.google.android.location.util.LocationAccuracyInjectorService
pm enable com.google.android.gms/com.google.android.location.wearable.WearableLocationService
pm enable com.google.android.gms/com.google.android.gms.locationsharing.service.LocationSharingSettingInjectorService
pm enable com.google.android.gms/com.google.android.gms.locationsharing.service.LocationSharingService
pm enable com.google.android.gms/com.google.android.gms.semanticlocation.service.SemanticLocationService
pm enable com.google.android.gms/com.google.android.gms.games.chimera.GamesSignInIntentServiceProxy
pm enable com.google.android.gms/com.google.android.gms.games.chimera.GamesSyncServiceNotificationProxy
pm enable com.google.android.gms/com.google.android.gms.games.chimera.GamesUploadServiceProxy
pm enable com.google.android.gms/com.google.android.gms.gp.gameservice.GameService
pm enable com.google.android.gms/com.google.android.gms.gp.gameservice.GameSessionService
pm enable com.google.android.gms/com.google.android.gms.chimera.GmsApiServiceNoInstantApps
pm enable com.google.android.gms/com.google.android.gms.chimera.PersistentApiServiceNoInstantApps
pm enable com.google.android.gms/com.google.android.gms.instantapps.service.InstantAppsService
pm enable com.google.android.gms/com.google.android.gms.chimera.UiApiServiceNoInstantApps
