#!/system/bin/sh
# Copyright (c) 2025, Noah Y. & Xaiphon

CON_PATH="/sdcard/Android/SpeedSaver"

# Wait until boot completed
    until [ $(resetprop sys.boot_completed) -eq 1 ] &&
        [ -d /sdcard ]; do
        sleep 10
    done

# Check if the directory exists
if [ -d "$CON_PATH" ]; then
    # Delete the directory and all its contents
    rm -rf "$CON_PATH"
fi

# Renove global table modifications
settings delete global cached_apps_freezer
#settings delete global enable_screen_on_proximity_sensor
settings delete global fstrim_mandatory_interval

# Reverse deactivation of Android Rescue Party
setprop persist.sys.disable_rescue false
resetprop -p persist.sys.disable_rescue false

# Enable GMS services
#/system/bin/sh
su -c pm enable com.google.android.gms/.ads.settings.AdsSettingsActivity
su -c pm enable com.google.android.gms/com.google.android.location.places.ui.aliaseditor.AliasEditorActivity
su -c pm enable com.google.android.gms/com.google.android.location.places.ui.aliaseditor.AliasEditorMapActivity
su -c pm enable com.google.android.gms/com.google.android.location.settings.ActivityRecognitionPermissionActivity
su -c pm enable com.google.android.gms/com.google.android.location.settings.GoogleLocationSettingsActivity
su -c pm enable com.google.android.gms/com.google.android.location.settings.LocationHistorySettingsActivity
su -c pm enable com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity
su -c pm enable com.google.android.gms/.usagereporting.settings.UsageReportingActivity
su -c pm enable com.google.android.gms/.googlehelp.helpactivities.SystemAppTrampolineActivity
su -c pm enable com.google.android.gms/.feedback.AnnotateScreenshotActivity
su -c pm enable com.google.android.gms/.ads.adinfo.AdvertisingInfoContentProvider
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingContentProvider
su -c pm enable com.google.android.gms/com.google.android.location.internal.LocationContentProvider
su -c pm enable com.google.android.gms/.common.stats.net.contentprovider.NetworkUsageContentProvider
su -c pm enable com.google.android.gms/.ads.config.GServicesChangedReceiver
su -c pm enable com.google.android.gms/com.google.android.contextmanager.systemstate.SystemStateReceiver
su -c pm enable com.google.android.gms/.ads.jams.SystemEventReceiver
su -c pm enable com.google.android.gms/.ads.config.FlagsReceiver
su -c pm enable com.google.android.gms/.ads.social.DoritosReceiver
su -c pm enable com.google.android.gms/.analytics.AnalyticsReceiver
su -c pm enable com.google.android.gms/.analytics.internal.GServicesChangedReceiver
su -c pm enable com.google.android.gms/.common.analytics.CoreAnalyticsReceiver
su -c pm enable com.google.android.gms/.common.stats.GmsCoreStatsServiceLauncher
su -c pm enable com.google.android.gms/com.google.android.location.internal.AnalyticsSamplerReceiver
su -c pm enable com.google.android.gms/.checkin.CheckinService$ActiveReceiver
su -c pm enable com.google.android.gms/.checkin.CheckinService$ClockworkFallbackReceiver
su -c pm enable com.google.android.gms/.checkin.CheckinService$ImposeReceiver
su -c pm enable com.google.android.gms/.checkin.CheckinService$SecretCodeReceiver
su -c pm enable com.google.android.gms/.checkin.CheckinService$TriggerReceiver
su -c pm enable com.google.android.gms/.checkin.EventLogService$Receiver
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.ExternalChangeReceiver
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.GcmRegistrationReceiver
su -c pm enable com.google.android.gms/com.google.android.location.copresence.GcmRegistrationReceiver
su -c pm enable com.google.android.gms/com.google.android.location.copresence.GservicesBroadcastReceiver
su -c pm enable com.google.android.gms/com.google.android.location.internal.LocationProviderEnabler
su -c pm enable com.google.android.gms/com.google.android.location.internal.NlpNetworkProviderSettingsUpdateReceiver
su -c pm enable com.google.android.gms/com.google.android.location.network.ConfirmAlertActivity$LocationModeChangingReceiver
su -c pm enable com.google.android.gms/com.google.android.location.places.ImplicitSignalsReceiver
su -c pm enable com.google.android.gms/com.google.android.libraries.social.mediamonitor.MediaMonitor
su -c pm enable com.google.android.gms/.location.copresence.GcmBroadcastReceiver
su -c pm enable com.google.android.gms/.location.reporting.service.GcmBroadcastReceiver
su -c pm enable com.google.android.gms/.social.location.GservicesBroadcastReceiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService$Receiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService$OtaPolicyReceiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService$SecretCodeReceiver
su -c pm enable com.google.android.gms/.update.SystemUpdateService$ActiveReceiver
su -c pm enable com.google.android.gms/com.google.android.contextmanager.service.ContextManagerService
su -c pm enable com.google.android.gms/.ads.AdRequestBrokerService
su -c pm enable com.google.android.gms/.ads.GservicesValueBrokerService
su -c pm enable com.google.android.gms/.ads.identifier.service.AdvertisingIdNotificationService
su -c pm enable com.google.android.gms/.ads.identifier.service.AdvertisingIdService
su -c pm enable com.google.android.gms/.ads.jams.NegotiationService
su -c pm enable com.google.android.gms/.ads.pan.PanService
su -c pm enable com.google.android.gms/.ads.social.GcmSchedulerWakeupService
su -c pm enable com.google.android.gms/.analytics.AnalyticsService
su -c pm enable com.google.android.gms/.analytics.internal.PlayLogReportingService
su -c pm enable com.google.android.gms/.analytics.service.AnalyticsService
su -c pm enable com.google.android.gms/.analytics.service.PlayLogMonitorIntervalService
su -c pm enable com.google.android.gms/.analytics.service.RefreshEnabledStateService
su -c pm enable com.google.android.gms/.auth.be.proximity.authorization.userpresence.UserPresenceService
su -c pm enable com.google.android.gms/.common.analytics.CoreAnalyticsIntentService
su -c pm enable com.google.android.gms/.common.stats.GmsCoreStatsService
su -c pm enable com.google.android.gms/.backup.BackupStatsService
su -c pm enable com.google.android.gms/.deviceconnection.service.DeviceConnectionAsyncService
su -c pm enable com.google.android.gms/.deviceconnection.service.DeviceConnectionServiceBroker
su -c pm enable com.google.android.gms/.wallet.service.analytics.AnalyticsIntentService
su -c pm enable com.google.android.gms/.checkin.CheckinService
su -c pm enable com.google.android.gms/.checkin.EventLogService
su -c pm enable com.google.android.gms/com.google.android.location.internal.AnalyticsUploadIntentService
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.DeleteHistoryService
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.DispatchingService
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.InternalPreferenceServiceDoNotUse
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.LocationHistoryInjectorService
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingAndroidService
su -c pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingSyncService
su -c pm enable com.google.android.gms/com.google.android.location.activity.HardwareArProviderService
su -c pm enable com.google.android.gms/com.google.android.location.fused.FusedLocationService
su -c pm enable com.google.android.gms/com.google.android.location.fused.service.FusedProviderService
su -c pm enable com.google.android.gms/com.google.android.location.geocode.GeocodeService
su -c pm enable com.google.android.gms/com.google.android.location.geofencer.service.GeofenceProviderService
su -c pm enable com.google.android.gms/com.google.android.location.internal.GoogleLocationManagerService
su -c pm enable com.google.android.gms/com.google.android.location.places.PlaylogService
su -c pm enable com.google.android.gms/com.google.android.location.places.service.GeoDataService
su -c pm enable com.google.android.gms/com.google.android.location.places.service.PlaceDetectionService
su -c pm enable com.google.android.gms/com.google.android.libraries.social.mediamonitor.MediaMonitorIntentService
su -c pm enable com.google.android.gms/.config.ConfigService
su -c pm enable com.google.android.gms/.stats.PlatformStatsCollectorService
su -c pm enable com.google.android.gms/.usagereporting.service.UsageReportingService
su -c pm enable com.google.android.gms/.update.SystemUpdateService
su -c pm enable com.google.android.gms/com.google.android.location.network.ConfirmAlertActivity
su -c pm enable com.google.android.gms/com.google.android.location.network.LocationProviderChangeReceiver
su -c pm enable com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService
su -c pm enable com.google.android.gms/com.google.android.location.internal.PendingIntentCallbackService
su -c pm enable com.google.android.gms/com.google.android.location.network.NetworkLocationService
su -c pm enable com.google.android.gms/com.google.android.location.util.PreferenceService
su -c pm enable com.google.android.gms/.fitness.settings.FitnessSettingsActivity
su -c pm enable com.google.android.gms/.fitness.sync.FitnessContentProvider
su -c pm enable com.google.android.gms/.fitness.disconnect.FitDisconnectReceiver
su -c pm enable com.google.android.gms/.fitness.sensors.sample.CollectSensorReceiver
su -c pm enable com.google.android.gms/.fitness.service.FitnessInitReceiver
su -c pm enable com.google.android.gms/.fitness.wearables.WearableSyncServiceReceiver
su -c pm enable com.google.android.gms/.fitness.disconnect.FitCleanupService
su -c pm enable com.google.android.gms/.fitness.sensors.activity.ActivityRecognitionService
su -c pm enable com.google.android.gms/.fitness.sensors.floorchange.FloorChangeRecognitionService
su -c pm enable com.google.android.gms/.fitness.sensors.sample.CollectSensorService
su -c pm enable com.google.android.gms/.fitness.service.DebugIntentService
su -c pm enable com.google.android.gms/.fitness.service.ble.FitBleBroker
su -c pm enable com.google.android.gms/.fitness.service.config.FitConfigBroker
su -c pm enable com.google.android.gms/.fitness.service.history.FitHistoryBroker
su -c pm enable com.google.android.gms/.fitness.service.internal.FitInternalBroker
su -c pm enable com.google.android.gms/.fitness.service.proxy.FitProxyBroker
su -c pm enable com.google.android.gms/.fitness.service.recording.FitRecordingBroker
su -c pm enable com.google.android.gms/.fitness.service.sensors.FitSensorsBroker
su -c pm enable com.google.android.gms/.fitness.service.sessions.FitSessionsBroker
su -c pm enable com.google.android.gms/.fitness.store.maintenance.StoreMaintenanceService
su -c pm enable com.google.android.gms/.fitness.sync.FitnessSyncAdapterService
su -c pm enable com.google.android.gms/.fitness.wearables.WearableSyncService
su -c pm enable com.google.android.gms/.car.BroadcastRedirectActivity
su -c pm enable com.google.android.gms/.car.CarErrorDisplayActivity
su -c pm enable com.google.android.gms/.car.CarHomeActivity
su -c pm enable com.google.android.gms/.car.CarHomeActivity1
su -c pm enable com.google.android.gms/.car.CarHomeActivity2
su -c pm enable com.google.android.gms/.car.CarServiceSettingsActivity
su -c pm enable com.google.android.gms/.car.FirstActivity
su -c pm enable com.google.android.gms/.car.SetupActivity
su -c pm enable com.google.android.gms/.car.CarIntentService
su -c pm enable com.google.android.gms/.car.CarService
su -c pm enable com.google.android.gms/.car.InCallServiceImpl
su -c pm enable com.google.android.gms/.car.VoiceActionService
su -c pm enable com.google.android.gms/.car.diagnostics.CrashReporterService
su -c pm enable com.google.android.gms/.feedback.FeedbackActivity
su -c pm enable com.google.android.gms/.feedback.IntentListenerFeedbackActivity
su -c pm enable com.google.android.gms/.feedback.PreviewActivity
su -c pm enable com.google.android.gms/.feedback.PreviewScreenshotActivity
su -c pm enable com.google.android.gms/.feedback.ShowTextActivity
su -c pm enable com.google.android.gms/.feedback.SuggestionsActivity
su -c pm enable com.google.android.gms/.feedback.FeedbackConnectivityReceiver
su -c pm enable com.google.android.gms/.feedback.FeedbackAsyncService
su -c pm enable com.google.android.gms/.feedback.FeedbackService
su -c pm enable com.google.android.gms/.feedback.LegacyBugReportService
su -c pm enable com.google.android.gms/.feedback.SendService
su -c pm enable com.google.android.gms/.googlehelp.helpactivities.ClickToCallActivity
su -c pm enable com.google.android.gms/.googlehelp.helpactivities.EmailActivity
su -c pm enable com.google.android.gms/.googlehelp.helpactivities.HelpActivity
su -c pm enable com.google.android.gms/.googlehelp.helpactivities.OpenHangoutActivity
su -c pm enable com.google.android.gms/.googlehelp.helpactivities.OpenHelpActivity
su -c pm enable com.google.android.gms/.googlehelp.helpactivities.RealtimeSupportClassifierActivity
su -c pm enable com.google.android.gms/.googlehelp.webview.GoogleHelpWebViewActivity
su -c pm enable com.google.android.gms/.googlehelp.GcmBroadcastReceiver
su -c pm enable com.google.android.gms/.googlehelp.metrics.ConnectivityBroadcastReceiver
su -c pm enable com.google.android.gms/.googlehelp.metrics.MetricsReportService
su -c pm enable com.google.android.gms/.googlehelp.metrics.ReportBatchedMetricsService
su -c pm enable com.google.android.gms/.googlehelp.service.ChatStatusUpdateService
su -c pm enable com.google.android.gms/.googlehelp.service.ClearHelpHistoryIntentService
su -c pm enable com.google.android.gms/.googlehelp.service.GoogleHelpService
su -c pm enable com.google.android.gms/.googlehelp.service.VideoCallStatusUpdateService
su -c pm enable com.google.android.gms/.kids.account.AccountRemovalConfirmActivity
su -c pm enable com.google.android.gms/.kids.account.AccountSetupActivity
su -c pm enable com.google.android.gms/.kids.account.ShowAppsActivity
su -c pm enable com.google.android.gms/.kids.account.activities.RegisterProfileOwnerActivity
su -c pm enable com.google.android.gms/.kids.creation.activities.FamilyCreationActivity
su -c pm enable com.google.android.gms/.kids.chimera.KidsDataProviderProxy
su -c pm enable com.google.android.gms/.kids.account.receiver.ProfileOwnerReceiver
su -c pm enable com.google.android.gms/.kids.chimera.AccountChangeReceiverProxy
su -c pm enable com.google.android.gms/.kids.chimera.AccountSetupCompletedReceiverProxy
su -c pm enable com.google.android.gms/.kids.chimera.DeviceTimeAndDateChangeReceiverProxy
su -c pm enable com.google.android.gms/.kids.chimera.InternalEventReceiverLmpProxy
su -c pm enable com.google.android.gms/.kids.chimera.InternalEventReceiverProxy
su -c pm enable com.google.android.gms/.kids.chimera.LocationModeChangedReceiverProxy
su -c pm enable com.google.android.gms/.kids.chimera.PackageChangedReceiverProxy
su -c pm enable com.google.android.gms/.kids.chimera.SystemEventReceiverProxy
su -c pm enable com.google.android.gms/.kids.chimera.LongRunningServiceProxy
su -c pm enable com.google.android.gms/.kids.common.sync.ManualSyncReceiver
su -c pm enable com.google.android.gms/.kids.GcmReceiverService
su -c pm enable com.google.android.gms/.kids.chimera.AccountSetupServiceProxy
su -c pm enable com.google.android.gms/.kids.chimera.KidsApiServiceProxy
su -c pm enable com.google.android.gms/.kids.chimera.KidsDataSyncServiceProxy
su -c pm enable com.google.android.gms/.kids.chimera.KidsServiceProxy
su -c pm enable com.google.android.gms/.kids.chimera.SlowOperationServiceProxy
su -c pm enable com.google.android.gms/.kids.chimera.TimeoutsSystemAlertServiceProxy
su -c pm enable com.google.android.gms/.kids.device.RingService
su -c pm enable com.google.android.gms/.nearby.messages.settings.NearbyMessagesAppOptInActivity
su -c pm enable com.google.android.gms/.nearby.settings.NearbyAccessActivity
su -c pm enable com.google.android.gms/.nearby.settings.NearbySettingsActivity
su -c pm enable com.google.android.gms/.nearby.messages.NearbyMessagesBroadcastReceiver
su -c pm enable com.google.android.gms/.nearby.settings.NearbyAppUninstallReceiver
su -c pm enable com.google.android.gms/.nearby.bootstrap.service.NearbyBootstrapService
su -c pm enable com.google.android.gms/.nearby.connection.service.NearbyConnectionsAndroidService
su -c pm enable com.google.android.gms/.nearby.connection.service.NearbyConnectionsAsyncService
su -c pm enable com.google.android.gms/.nearby.messages.service.NearbyMessagesService
su -c pm enable com.google.android.gms/.nearby.sharing.service.NearbySharingService
su -c pm enable com.google.android.gms/.phenotype.receiver.PhenotypeBroadcastReceiver
su -c pm enable com.google.android.gms/.phenotype.service.PhenotypeCommitService
su -c pm enable com.google.android.gms/.phenotype.service.PhenotypeIntentService
su -c pm enable com.google.android.gms/.phenotype.service.PhenotypeService
su -c pm enable com.google.android.gms/.phenotype.service.sync.PhenotypeConfigurator
su -c pm enable com.google.android.gms/.phenotype.service.util.PhenotypeDebugService
su -c pm enable com.google.android.gms/.pseudonymous.service.PseudonymousIdIntentService
su -c pm enable com.google.android.gms/.pseudonymous.service.PseudonymousIdService
su -c pm enable com.google.android.gms/.photos.autobackup.ui.AutoBackupSettingsActivity
su -c pm enable com.google.android.gms/.photos.autobackup.ui.AutoBackupSettingsRedirectActivity
su -c pm enable com.google.android.gms/.photos.autobackup.ui.LocalFoldersBackupSettings
su -c pm enable com.google.android.gms/.photos.autobackup.ui.promo.AutoBackupPromoActivity
su -c pm enable com.google.android.gms/.photos.InitializePhotosIntentReceiver
su -c pm enable com.google.android.gms/.photos.autobackup.AutoBackupWorkService
su -c pm enable com.google.android.gms/.photos.autobackup.service.AutoBackupService
su -c pm enable com.google.android.gms/.playlog.service.MonitorAlarmReceiver
su -c pm enable com.google.android.gms/.playlog.service.WallClockChangedReceiver
su -c pm enable com.google.android.gms/.playlog.service.MonitorService
su -c pm enable com.google.android.gms/.playlog.service.PlayLogBrokerService
su -c pm enable com.google.android.gms/.playlog.service.PlayLogIntentService
su -c pm enable com.google.android.gms/.playlog.uploader.RequestUploadService
su -c pm enable com.google.android.gms/.playlog.uploader.UploaderService
su -c pm enable com.google.android.gms/.plus.activity.AccountSignUpActivity
su -c pm enable com.google.android.gms/.plus.apps.ListAppsActivity
su -c pm enable com.google.android.gms/.plus.apps.ManageAppActivity
su -c pm enable com.google.android.gms/.plus.apps.ManageDeviceActivity
su -c pm enable com.google.android.gms/.plus.apps.ManageMomentActivity
su -c pm enable com.google.android.gms/.plus.audience.AclSelectionActivity
su -c pm enable com.google.android.gms/.plus.audience.AudienceSearchActivity
su -c pm enable com.google.android.gms/.plus.audience.CircleCreationActivity
su -c pm enable com.google.android.gms/.plus.audience.CircleSelectionActivity
su -c pm enable com.google.android.gms/.plus.audience.FaclSelectionActivity
su -c pm enable com.google.android.gms/.plus.audience.UpdateActionOnlyActivity
su -c pm enable com.google.android.gms/.plus.audience.UpdateCirclesActivity
su -c pm enable com.google.android.gms/.plus.circles.AddToCircleConsentActivity
su -c pm enable com.google.android.gms/.plus.oob.PlusActivity
su -c pm enable com.google.android.gms/.plus.oob.UpgradeAccountActivity
su -c pm enable com.google.android.gms/.plus.oob.UpgradeAccountInfoActivity
su -c pm enable com.google.android.gms/.plus.plusone.PlusOneActivity
su -c pm enable com.google.android.gms/.plus.sharebox.AddToCircleActivity
su -c pm enable com.google.android.gms/.plus.sharebox.ReplyBoxActivity
su -c pm enable com.google.android.gms/.plus.sharebox.ShareBoxActivity
su -c pm enable com.google.android.gms/.plus.provider.PlusProvider
su -c pm enable com.google.android.gms/.plus.service.DefaultIntentService
su -c pm enable com.google.android.gms/.plus.service.ImageIntentService
su -c pm enable com.google.android.gms/.plus.service.OfflineActionSyncAdapterService
su -c pm enable com.google.android.gms/.plus.service.PlusService
su -c pm enable com.google.android.gms/.wifi.gatherer2.receiver.WifiStateChangeReceiver
su -c pm enable com.google.android.gms/.wifi.gatherer2.receiver.GoogleAccountChangeReceiver
su -c pm enable com.google.android.gms/.wifi.gatherer2.service.GcmReceiverService
su -c pm enable com.google.android.gms/.wifi.gatherer2.service.WifiUpdateRetryTaskService
su -c pm enable com.google.android.gms/.wifi.gatherer2.service.KeyManagerServce
su -c pm enable com.google.android.gms/.ads.measurement.GmpConversionTrackingBrokerService
su -c pm enable com.google.android.gms/.measurement.service.MeasurementBrokerService
su -c pm enable com.google.android.gms/.perfprofile.uploader.PerfProfileCollectorService
su -c pm enable com.google.android.gms/.perfprofile.uploader.RequestPerfProfileCollectionService
su -c pm enable com.google.android.gsf/.update.SystemUpdateActivity
su -c pm enable com.google.android.gsf/.update.SystemUpdatePanoActivity
su -c pm enable com.google.android.gsf/com.google.android.gsf.checkin.CheckinService\$Receiver
su -c pm enable com.google.android.gsf/com.google.android.gsf.checkin.CheckinService\$SecretCodeReceiver
su -c pm enable com.google.android.gsf/com.google.android.gsf.checkin.CheckinService\$TriggerReceiver
su -c pm enable com.google.android.gsf/.checkin.EventLogService$Receiver
su -c pm enable com.google.android.gsf/.update.SystemUpdateService$Receiver
su -c pm enable com.google.android.gsf/.update.SystemUpdateService$SecretCodeReceiver
su -c pm enable com.google.android.gsf/.checkin.CheckinService
su -c pm enable com.google.android.gsf/.checkin.EventLogService
su -c pm enable com.google.android.gsf/.update.SystemUpdateService
su -c "pm enable com.google.android.gms/com.google.android.gms.ads.identifier.service.AdvertisingIdNotificationService"
su -c "pm enable com.google.android.gms/com.google.android.gms.ads.identifier.service.AdvertisingIdService"
su -c "pm enable com.google.android.gms/com.google.android.gms.nearby.mediums.nearfieldcommunication.NfcAdvertisingService"
su -c "pm enable com.google.android.gms/com.google.android.gms.analytics.AnalyticsService"
su -c "pm enable com.google.android.gms/com.google.android.gms.analytics.AnalyticsTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.analytics.internal.PlayLogReportingService"
su -c "pm enable com.google.android.gms/com.google.android.gms.stats.eastworld.EastworldService"
su -c "pm enable com.google.android.gms/com.google.android.gms.stats.service.DropBoxEntryAddedService"
su -c "pm enable com.google.android.gms/com.google.android.gms.stats.PlatformStatsCollectorService"
su -c "pm enable com.google.android.gms/com.google.android.gms.common.stats.GmsCoreStatsService"
su -c "pm enable com.google.android.gms/com.google.android.gms.common.stats.StatsUploadService"
su -c "pm enable com.google.android.gms/com.google.android.gms.backup.stats.BackupStatsService"
su -c "pm enable com.google.android.gms/com.google.android.gms.checkin.CheckinApiService"
su -c "pm enable com.google.android.gms/com.google.android.gms.checkin.CheckinService"
su -c "pm enable com.google.android.gms/com.google.android.gms.tron.CollectionService"
su -c "pm enable com.google.android.gms/com.google.android.gms.common.config.PhenotypeCheckinService"
su -c "pm enable com.google.android.gms/com.google.android.location.internal.server.HardwareArProviderService"
su -c "pm enable com.google.android.gms/com.google.android.gms.feedback.FeedbackAsyncService"
su -c "pm enable com.google.android.gms/com.google.android.gms.feedback.LegacyBugReportService"
su -c "pm enable com.google.android.gms/com.google.android.gms.feedback.OfflineReportSendTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.googlehelp.metrics.ReportBatchedMetricsGcmTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.analytics.internal.PlayLogReportingService"
su -c "pm enable com.google.android.gms/com.google.android.gms.locationsharingreporter.service.reporting.periodic.PeriodicReporterMonitoringService"
su -c "pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingAndroidService"
su -c "pm enable com.google.android.gms/com.google.android.location.reporting.service.ReportingSyncService"
su -c "pm enable com.google.android.gms/com.google.android.gms.common.stats.net.NetworkReportService"
su -c "pm enable com.google.android.gms/com.google.android.gms.presencemanager.service.PresenceManagerPresenceReportService"
su -c "pm enable com.google.android.gms/com.google.android.gms.usagereporting.service.UsageReportingIntentService"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRoute2ProviderService"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRoute2ProviderService_Isolated"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRoute2ProviderService_Persistent"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRouteProviderService"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRouteProviderService_Isolated"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastMediaRouteProviderService_Persistent"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastRemoteDisplayProviderService"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastRemoteDisplayProviderService_Isolated"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.media.CastRemoteDisplayProviderService_Persistent"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.service.CastPersistentService_Persistent"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.service.CastSocketMultiplexerLifeCycleService"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.service.CastSocketMultiplexerLifeCycleService_Isolated"
su -c "pm enable com.google.android.gms/com.google.android.gms.cast.service.CastSocketMultiplexerLifeCycleService_Persistent"
su -c "pm enable com.google.android.gms/com.google.android.gms.chimera.CastPersistentBoundBrokerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.nearby.messages.debug.DebugPokeService"
su -c "pm enable com.google.android.gms/com.google.android.gms.clearcut.debug.ClearcutDebugDumpService"
su -c "pm enable com.google.firebase.components.ComponentDiscoveryService"
su -c "pm enable com.google.android.gms/com.google.android.gms.nearby.discovery.service.DiscoveryService"
su -c "pm enable com.google.android.gms/com.google.mlkit.common.internal.MlKitComponentDiscoveryService"
su -c "pm enable com.google.android.gms/com.google.android.gms.geotimezone.GeoTimeZoneService"
su -c "pm enable com.google.android.gms/com.google.android.gms.location.geocode.GeocodeService"
su -c "pm enable com.google.android.gms/com.google.android.gms.chimera.GmsIntentOperationService_AuthAccountIsolated com.google.android.gms/com.google.android.gms.chimera.GmsIntentOperationService_AuthAccountIsolate"
su -c "pm enable com.google.android.gms/com.google.android.gms.chimera.PersistentApiService_AuthAccountIsolated"
su -c "pm enable com.google.android.gms/com.google.android.gms.chimera.PersistentIntentOperationService_AuthAccountIsolated"
su -c "pm enable com.google.android.gms/com.google.android.gms.auth.folsom.service.FolsomPublicKeyUpdateService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fonts.update.UpdateSchedulerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.icing.proxy.IcingInternalCorporaUpdateService"
su -c "pm enable com.google.android.gms/com.google.android.gms.instantapps.routing.DomainFilterUpdateService"
su -c "pm enable com.google.android.gms/com.google.android.gms.mobiledataplan.service.PeriodicUpdaterService"
su -c "pm enable com.google.android.gms/com.google.android.gms.phenotype.service.sync.PackageUpdateTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.update.SystemUpdateGcmTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.update.SystemUpdateService"
su -c "pm enable com.google.android.gms/com.google.android.gms.update.UpdateFromSdCardService"
su -c "pm enable com.google.android.gms/com.google.android.gms.backup.wear.BackupSettingsListenerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.dck.service.DckWearableListenerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncAccountService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncConfigService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncConnectionService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncMessageService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.wearables.WearableSyncService"
su -c "pm enable com.google.android.gms/com.google.android.gms.wearable.service.WearableControlService"
su -c "pm enable com.google.android.gms/com.google.android.gms.wearable.service.WearableService"
#su -c "pm enable com.google.android.gms/com.google.android.gms.nearby.fastpair.service.WearableDataListenerService"
su -c "pm enable com.google.android.gms/com.google.android.location.wearable.WearableLocationService"
su -c "pm enable com.google.android.gms/com.google.android.location.fused.wearable.GmsWearableListenerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.mdm.services.MdmPhoneWearableListenerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.tapandpay.wear.WearProxyService"
su -c "pm enable com.google.android.gms/com.google.android.gms.auth.trustagent.GoogleTrustAgent"
su -c "pm enable com.google.android.gms/com.google.android.gms.trustagent.api.bridge.TrustAgentBridgeService"
su -c "pm enable com.google.android.gms/com.google.android.gms.trustagent.api.state.TrustAgentState"
su -c "pm enable com.google.android.gms/com.google.android.gms.enpromo.PromoInternalPersistentService"
su -c "pm enable com.google.android.gms/com.google.android.gms.enpromo.PromoInternalService"
su -c "pm enable com.google.android.gms/com.google.android.gms.thunderbird.EmergencyLocationService" 
su -c "pm enable com.google.android.gms/com.google.android.gms.thunderbird.EmergencyPersistentService"
su -c "pm enable com.google.android.gms/com.google.android.gms.kids.chimera.KidsServiceProxy"
su -c "pm enable com.google.android.gms/com.google.android.gms.personalsafety.service.PersonalSafetyService"
ui_print "✦ Disabled emergency features and child safety services."
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.cache.DataUpdateListenerCacheService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.ble.FitBleBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.config.FitConfigBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.goals.FitGoalsBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.history.FitHistoryBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.internal.FitInternalBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.proxy.FitProxyBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.recording.FitRecordingBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.sensors.FitSensorsBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.service.sessions.FitSessionsBroker"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.sensors.sample.CollectSensorService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.sync.FitnessSyncAdapterService" 
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.sync.SyncGcmTaskService"
ui_print "✦ Disabled Google Fit health tracking services."
su -c "pm enable com.google.android.gms/com.google.android.gms.nearby.bootstrap.service.NearbyBootstrapService"
su -c "pm enable com.google.android.gms/com.google.android.gms.nearby.connection.service.NearbyConnectionsAndroidService"
su -c "pm enable com.google.android.gms/com.google.location.nearby.direct.service.NearbyDirectService"
su -c "pm enable com.google.android.gms/com.google.android.gms.nearby.messages.service.NearbyMessagesService"
su -c "pm enable com.google.android.gms/com.google.android.gms.analytics.internal.PlayLogReportingService"
su -c "pm enable com.google.android.gms/com.google.android.gms.romanesco.ContactsLoggerUploadService"
su -c "pm enable com.google.android.gms/com.google.android.gms.magictether.logging.DailyMetricsLoggerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.checkin.EventLogService"
su -c "pm enable com.google.android.gms/com.google.android.gms.backup.component.FullBackupJobLoggerService"
su -c "pm enable com.google.android.gms/com.google.android.gms.security.safebrowsing.SafeBrowsingUpdateTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.security.verifier.ApkUploadService"
su -c "pm enable com.google.android.gms/com.google.android.gms.security.verifier.InternalApkUploadService"
su -c "pm enable com.google.android.gms/com.google.android.gms.security.snet.SnetIdleTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.security.snet.SnetNormalTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.security.snet.SnetService"
su -c "pm enable com.google.android.gms/com.google.android.gms.tapandpay.security.StorageKeyCacheService"
su -c "pm enable com.google.android.gms/com.google.android.gms.droidguard.DroidGuardGcmTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.pay.security.storagekey.service.StorageKeyCacheService"
su -c "pm enable com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.tapandpay.globalactions.QuickAccessWalletService"
su -c "pm enable com.google.android.gms/com.google.android.gms.tapandpay.globalactions.WalletQuickAccessWalletService"
su -c "pm enable com.google.android.gms/com.google.android.gms.pay.gcmtask.PayGcmTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.pay.hce.service.PayHceService"
su -c "pm enable com.google.android.gms/com.google.android.gms.pay.notifications.PayNotificationService"
su -c "pm enable com.google.android.gms/com.google.android.gms.wallet.service.PaymentService"
su -c "pm enable com.google.android.gms/com.google.android.gms.wallet.service.WalletGcmTaskService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.cache.DataUpdateListenerCacheService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.sensors.sample.CollectSensorService"
su -c "pm enable com.google.android.gms/com.google.android.gms.fitness.sync.SyncGcmTaskService"
su -c "pm enable com.google.android.gms/com.google.android.location.fused.FusedLocationService"
su -c "pm enable com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService"
su -c "pm enable com.google.android.gms/com.google.android.location.network.NetworkLocationService"
su -c "pm enable com.google.android.gms/com.google.android.location.persistent.LocationPersistentService"
su -c "pm enable com.google.android.gms/com.google.android.location.reporting.service.LocationHistoryInjectorService"
su -c "pm enable com.google.android.gms/com.google.android.location.util.LocationAccuracyInjectorService"
su -c "pm enable com.google.android.gms/com.google.android.location.wearable.WearableLocationService"
su -c "pm enable com.google.android.gms/com.google.android.gms.locationsharing.service.LocationSharingSettingInjectorService"
su -c "pm enable com.google.android.gms/com.google.android.gms.locationsharing.service.LocationSharingService"
su -c "pm enable com.google.android.gms/com.google.android.gms.semanticlocation.service.SemanticLocationService"
su -c "pm enable com.google.android.gms/com.google.android.gms.games.chimera.GamesSignInIntentServiceProxy"
su -c "pm enable com.google.android.gms/com.google.android.gms.games.chimera.GamesSyncServiceNotificationProxy"
su -c "pm enable com.google.android.gms/com.google.android.gms.games.chimera.GamesUploadServiceProxy"
su -c "pm enable com.google.android.gms/com.google.android.gms.gp.gameservice.GameService"
su -c "pm enable com.google.android.gms/com.google.android.gms.gp.gameservice.GameSessionService"
su -c "pm enable com.google.android.gms/com.google.android.gms.chimera.GmsApiServiceNoInstantApps"
su -c "pm enable com.google.android.gms/com.google.android.gms.chimera.PersistentApiServiceNoInstantApps"
su -c "pm enable com.google.android.gms/com.google.android.gms.instantapps.service.InstantAppsService"
su -c "pm enable com.google.android.gms/com.google.android.gms.chimera.UiApiServiceNoInstantApps"
